# Numpy Exercise 1

### All of the questions in this exercise are attributed to rougier/numpy-100

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
# Print NumPy version
print("NumPy version:", np.__version__)

# Print configuration
np.show_config()

NumPy version: 2.3.1
{
  "Compilers": {
    "c": {
      "name": "msvc",
      "linker": "link",
      "version": "19.43.34808",
      "commands": "cl"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.1.2",
      "commands": "cython"
    },
    "c++": {
      "name": "msvc",
      "linker": "link",
      "version": "19.43.34808",
      "commands": "cl"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "scipy-openblas",
      "found": true,
      "version": "0.3.29",
      "detection method": "pkgconfig",
      "include directory": "C:/Users/runneradmin/AppData/Local/Temp/cibw-run-9tmma_o0/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include

c:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\numpy\__config__.py:155: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


#### 3. Create a null vector of size 10 (★☆☆)

In [5]:
# null vector =  a vector where all elements are zero
null_vector = np.zeros(10)
print(null_vector)
np.size (null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


10

#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
arr = np.zeros(10)
print (arr)
#Array creation functions (zeros, ones, empty) default to float64

#.nbytes: Total bytes consumed by the array data
#.size: Total number of elements
#.itemsize: Size in bytes of each element

print("Memory size in bytes:", arr.nbytes)

print("Memory size in bytes:", arr.size * arr.itemsize)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Memory size in bytes: 80
Memory size in bytes: 80


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [15]:

help(np.add)

#The signature tells you exactly how you're allowed to call the function and what parameters are available!

Help on ufunc in module numpy:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [16]:
arr2 = np.zeros(10)
print (arr2)
arr2[4] = 1
print (arr2)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)
 vector is simply a 1-dimensional array - a list of numbers arranged in a single row or colum

In [18]:
arr4 = np.arange(10, 50)
print(arr4)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [19]:
arr4 [::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [23]:
matrix = np.arange(9)
print(matrix)
print (np.size(matrix))
matrix2= matrix.reshape(3, 3)
print(matrix2)

[0 1 2 3 4 5 6 7 8]
9
[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [25]:
# Create the array
arr5 = np.array([1, 2, 0, 0, 4, 0])

# nonzero() elements
indices = np.nonzero(arr5)
print("Indices:", indices[0])

Indices: [0 1 4]


#### 11. Create a 3x3 identity matrix (★☆☆)

In [26]:
identity_matrix= np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [ ]:
# Create a 3x3x3 array with random values
array = np.random.rand(3, 3, 3)

print(array)

[[[0.55293997 0.71065361 0.44894114]
  [0.87711288 0.49017259 0.564482  ]
  [0.50911998 0.08083818 0.05350959]]

 [[0.51728551 0.06786749 0.25414244]
  [0.13627043 0.74371434 0.92339954]
  [0.38296909 0.46408796 0.82889287]]

 [[0.55468847 0.30030125 0.78780491]
  [0.72151885 0.8737857  0.1571338 ]
  [0.84338948 0.42402967 0.84740723]]]


In [39]:
# Create a 3x3x3 array with random integers between 0 and 10 
array = np.random.randint(0, 10, size=(3, 3, 3))

print(array)


[[[8 8 0]
  [1 9 9]
  [7 4 5]]

 [[8 4 5]
  [1 0 2]
  [7 6 2]]

 [[0 2 4]
  [9 2 5]
  [5 8 4]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [33]:
# Create a 10x10 array with random integers from 0 to 100 (exclusive)
array = np.random.randint(0, 100, size=(10, 10))

# Find minimum and maximum values
min_val = array.min()
max_val = array.max()

print("Array:\n", array)
print("Minimum value:", min_val)
print("Maximum value:", max_val)


Array:
 [[32 62  6 82 61 61 34  9 17 50]
 [26 94 86 53 18 14 10 99 51 82]
 [57 96 84 60  6 74 58 13 24 48]
 [95 86 85  6 71 77 64 74 37 15]
 [ 1 80 86 17 89 60 82 63 99 36]
 [50 39 92 83 38 58 78  5 95 72]
 [ 3 92 71 52 90  2 18 82 77 86]
 [ 5 24  3  1 17 89 48 64 76  0]
 [67  4 57 56 84 81 49 54 61 58]
 [36 55 93 45 31 99 50 20 86 32]]
Minimum value: 0
Maximum value: 99


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [37]:
vector = np.random.randint(0, 100, size=30)
mean_val = vector.mean()

print(np.size(vector))
print("Vector:\n", vector)
print("Mean value:", mean_val)

30
Vector:
 [96 42 57 37  5 24  1 12  1 98 46 15 89 88 19 88 32 76 87 29 16 24 68 99
 66 13 67 73 40  4]
Mean value: 47.06666666666667


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [38]:
# Create a 5x5 array filled with 1s
array = np.ones((5, 5), dtype=int)

# Set the inner elements to 0
array[1:-1, 1:-1] = 0

print(array)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
