# Numpy Exercise 2

### All of the questions in this exercise are attributed to rougier/numpy-100

In [1]:
import numpy as np

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [2]:
# Original array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print("Original array:")
print(arr)
print()


bordered_arr = np.pad(arr, pad_width=1, mode='constant', constant_values=0)

print("Bordered array:")
print(bordered_arr)
print()

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Bordered array:
[[0 0 0 0 0]
 [0 1 2 3 0]
 [0 4 5 6 0]
 [0 7 8 9 0]
 [0 0 0 0 0]]



In [ ]:
rows, cols = arr.shape
bordered2 = np.zeros((rows + 2, cols + 2), dtype=arr.dtype)
bordered2[1:-1, 1:-1] = arr
print("Using np.zeros() and slicing:")
print(bordered2)
print()

Using np.zeros() and slicing:
[[0 0 0 0 0]
 [0 1 2 3 0]
 [0 4 5 6 0]
 [0 7 8 9 0]
 [0 0 0 0 0]]



In [ ]:
demo_arr = np.array([[1, 2, 3],
                     [4, 5, 6]])

constant_pad = np.pad(demo_arr, pad_width=2, mode='constant', constant_values=0)
print("1. CONSTANT mode (fills with 0s):")
print(constant_pad)
print()

edge_pad = np.pad(demo_arr, pad_width=1, mode='edge')
print("2. EDGE mode (repeats edge values):")
print(edge_pad)
print()

reflect_pad = np.pad(demo_arr, pad_width=1, mode='reflect')
print("3. REFLECT mode (mirrors without repeating edge):")
print(reflect_pad)
print()

wrap_pad = np.pad(demo_arr, pad_width=2, mode='wrap')
print("5. WRAP mode (wraps around circularly):")
print(wrap_pad)
print()

1. CONSTANT mode (fills with 0s):
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 1 2 3 0 0]
 [0 0 4 5 6 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]

2. EDGE mode (repeats edge values):
[[1 1 2 3 3]
 [1 1 2 3 3]
 [4 4 5 6 6]
 [4 4 5 6 6]]

3. REFLECT mode (mirrors without repeating edge):
[[5 4 5 6 5]
 [2 1 2 3 2]
 [5 4 5 6 5]
 [2 1 2 3 2]]

5. WRAP mode (wraps around circularly):
[[2 3 1 2 3 1 2]
 [5 6 4 5 6 4 5]
 [2 3 1 2 3 1 2]
 [5 6 4 5 6 4 5]
 [2 3 1 2 3 1 2]
 [5 6 4 5 6 4 5]]



#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:

print(0 * np.nan)
#Any arithmetic operation with NaN results in NaN

print(np.nan == np.nan) #NaN is never equal to anything, including itself 

print(np.inf > np.nan) #(All comparisons with NaN return False (except != which returns True))

print(np.nan - np.nan) #NaN minus NaN is still NaN (indeterminate form)

print(np.nan in set([np.nan])) #np.nan in set([np.nan] - creates a set containing one NaN value

print(0.3 == 3 * 0.1) #3 * 0.1 has tiny rounding errors that make it slightly different from 0.3


nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [ ]:
matrix = np.diag([1, 2, 3, 4], k=-1) #k=-1 means one position below main diagonal
#k=0 is the diagonal; k=1 is a position above the diagonal
matrix

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [ ]:
matrix2 = np.zeros((5, 5), dtype=int)
values = [1, 2, 3, 4]
for i in range(4):  # 4 elements to place
    matrix2[i+1, i] = values[i]  # row i+1, column i (below diagonal)
print(matrix2)
print()

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]



#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
#matrix3 = np.zeros((8, 8), dtype=int)

rows = np.arange(8) # Column vector
cols = np.arange(8).reshape(-1, 1)  # Row vector
checkerboard3 = (rows + cols) % 2
print(checkerboard3)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [ ]:
# Shape of the array
shape = (6, 7, 8) #3D array with 336 values.

# Get the index of the 100th element (index 99)
#6 blocks; Each block has 7 rows,Each row has 8 columns.

index = np.unravel_index(99, shape)
print(index)


(np.int64(1), np.int64(5), np.int64(3))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [ ]:

np.tile([[0,1],[1,0]], (4,4))

#np.tile() repeats the array like tiles on a floor - taking the 2x2 pattern and repeating 4 times vertically & horizontally


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [ ]:
#Normalization means scaling values to a range between 0 and 1.

#normalized= [max(X)−min(X)]/[X−min(X)]

matrix = np.random.randint(1,50, size=[5,5])
print("Original matrix:\n", matrix)
print()

# Step 2: Normalize the matrix
print("min matrix:", np.min(matrix))
print ("max matrix:",np.max(matrix))
print()
normalized_matrix = (matrix - np.min(matrix)) / (np.max(matrix) - np.min(matrix))
normalized_matrix2 = (matrix -np.mean(matrix)) / np.std(matrix)
print("normalized_matrix:\n", normalized_matrix)
print("normalized_matrix:\n", normalized_matrix2)


NameError: name 'np' is not defined

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [ ]:

# Create custom dtype for RGBA color (4 unsigned bytes)
color_dtype = np.dtype([('r', np.uint8),
                        ('g', np.uint8),
                        ('b', np.uint8),
                        ('a', np.uint8)])
#np.uint8 = unsigned byte (values from 0 to 255).

# Create an array of colors using the custom dtype
colors = np.array([
    (255, 0, 0, 255),    # Red
    (0, 255, 0, 255),    # Green
    (0, 0, 255, 255),    # Blue
    (255, 255, 0, 128)   # Yellow with transparency
], dtype=color_dtype)

print(colors)


[(255,   0,   0, 255) (  0, 255,   0, 255) (  0,   0, 255, 255)
 (255, 255,   0, 128)]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:

# Create a 5x3 matrix (A)
A = np.random.randint(1,10, size=[5, 3])

# Create a 3x2 matrix (B)
B = np.random.randint(1,10, size=[3, 2])

# Perform matrix multiplication (5x2 result)
C = np.dot(A, B)

# Or equivalently using @ operator:
# C = A @ B

print(A)
print(B)
print(C)


[[3 5 4]
 [3 2 8]
 [4 6 8]
 [4 6 2]
 [3 1 9]]
[[5 7]
 [5 2]
 [4 2]]
[[56 39]
 [57 41]
 [82 56]
 [58 44]
 [56 41]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:

# 1D array
arr = np.array([1, 4, 6, 9, 2, 8, 3, 10])

# Negate elements between 3 and 8 (inclusive)
arr[(arr >= 4) & (arr <= 7)] *= -1

print(arr)

np.negative(arr, out=arr, where=(arr >= 4) & (arr <= 7))
#out=arr: updates the array in place.


[ 1 -4 -6  9  2  8  3 10]


array([ 1, -4, -6,  9,  2,  8,  3, 10])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1))
# the range = (0+1+2+3+4 = 10) then (-1)

10


In [ ]:
from numpy import *
#overwrites the built-in sum function with NumPy’s sum() ufunc 

print(sum(range(5),-1))
# -1 is interpreted as axis = -1 (last axis).
#Axis -1 on a 1D array means: sum over the whole array

# for 2d array : axis=0 (rows) - column sums ; axis=1 (columns) - row sums
# axis=-1 always refers to the innermost dimension, the last axis in the shape.


10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z = np.arange(5)  # Z = [0, 1, 2, 3, 4]

z1= Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
#Z<Z>Z


array([0., 1., 2., 3., 4.])

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:

np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
#.astype(int) → converts nan to an arbitrary integer then astype(float) converts the int back to float.


C:\Users\Administrator\AppData\Local\Temp\ipykernel_16972\2032225821.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
C:\Users\Administrator\AppData\Local\Temp\ipykernel_16972\2032225821.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
C:\Users\Administrator\AppData\Local\Temp\ipykernel_16972\2032225821.py:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)

In [ ]:

Z = np.array([-1.7, -0.2, 0.2, 1.7])
rounded = np.copysign(np.ceil(np.abs(Z)), Z)

truncated = np.trunc(Z)  # Truncates toward zero
whole = Z.astype(int)  # Also truncates toward zero

print(rounded)
print(truncated)
print(whole)

#np.abs(Z) → gets absolute values: [1.7, 0.2, 0.2, 1.7]
#np.ceil(...) → rounds up (away from 0): [2.0, 1.0, 1.0, 2.0]
#np.copysign(..., Z) → gives the original signs back: [-2.0, -1.0, 1.0, 2.0]


[-2. -1.  1.  2.]
[-1. -0.  0.  1.]
[-1  0  0  1]


#### 30. How to find common values between two arrays? (★☆☆)

In [ ]:

a = np.array([1, 2, 8, 4, 5])
b = np.array([4, 5, 6, 7, 8])

common = np.intersect1d(a, b)
#np.intersect1d(a, b) returns the sorted, unique values that are present in both arrays.

common2 = np.array([x for x in a if x in b])

print(common) 
print(common2)  


[4 5 8]
[8 4 5]
