# Numpy Exercise 5

### All of the questions in this exercise are attributed to rougier/numpy-100

#### 61. Find the nearest value from a given value in an array (★★☆)

In [11]:
import numpy as np

arr = np.array([1.5, 2.8, 4.1, 6.3, 8.7, 10.2])
target = 5.0

#argmin with absolute difference to find closest value in array.
nearest_idx = np.argmin(np.abs(arr - target))
nearest_value = arr[nearest_idx]

print(f"array: {arr}")
print(f"target: {target}")
print(f"Nearest value: {nearest_value} at index {nearest_idx}")

array: [ 1.5  2.8  4.1  6.3  8.7 10.2]
target: 5.0
Nearest value: 4.1 at index 2


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [9]:
a = np.array([[1, 2, 3]])  # Shape (1,3)
b = np.array([[4], [5], [6]])  # Shape (3,1)

# Using nditer
result = np.zeros((3, 3))
it = np.nditer([a, b, result], 
               flags=['multi_index'],
               op_flags=[['readonly'], ['readonly'], ['writeonly']])
for x, y, z in it:
    z[...] = x + y

print(f"Array a:\n {a}")
print(f"Array b:\n {b}")
print(f"Sum:\n {result}")

Array a:
 [[1 2 3]]
Array b:
 [[4]
 [5]
 [6]]
Sum:
 [[5. 6. 7.]
 [6. 7. 8.]
 [7. 8. 9.]]


#### 63. Create an array class that has a name attribute (★★☆)

In [ ]:
class NamedArray(np.ndarray): #custom NumPy array subclass that stores a name attribute.
    def __new__(cls, input_array, name=None):
        obj = np.asarray(input_array).view(cls)
        obj.name = name
        return obj
    
    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', None)
    
    def __repr__(self):
        return f"NamedArray('{self.name}'):\n{np.ndarray.__repr__(self)}"

# practical
named_arr = NamedArray([1, 2, 3, 4], name="my_vector")
print(named_arr)

[1 2 3 4]


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [13]:
X = np.array([1, 2, 3, 4, 5])
indices = np.array([0, 1, 1, 3, 3, 3])  # Repeated indices

print(f"Original X: {X}")
print(f"Indices: {indices}")

# Using np.add.at (handles repeated indices)
X_copy1 = X.copy()
np.add.at(X_copy1, indices, 1)
print(f"Result: {X_copy1}")

Original X: [1 2 3 4 5]
Indices: [0 1 1 3 3 3]
Result: [2 4 3 7 5]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [ ]:
X = np.array([10, 20, 30, 40, 50])
I = np.array([0, 2, 1, 2, 0])  # Indices where to accumulate
F = np.zeros(3)  # Target array

print(f"Values X: {X}")
print(f"Indices I: {I}")
print(f"Initial F: {F}")

# Using np.add.at:
F2 = F.copy()
np.add.at(F2, I, X)
print(f"Accumulated F: {F2}")

Values X: [10 20 30 40 50]
Indices I: [0 2 1 2 0]
Initial F: [0. 0. 0.]
Accumulated F: [60. 30. 60.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [ ]:
# sample image
np.random.seed(42)
image = np.random.randint(0, 256, (4, 4, 3), dtype=np.uint8)
print(f"Image shape: {image.shape}")

# Method 1: Reshape and use unique
colors_flat = image.reshape(-1, 3)
unique_colors = np.unique(colors_flat, axis=0)
num_unique = len(unique_colors)
print(f"Number of unique colors: {num_unique}")

Image shape: (4, 4, 3)
Number of unique colors: 16


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [23]:
arr_4d = np.random.randint(0, 10, (2, 3, 4, 5))
# print(arr_4d)
print(f"4D array shape: {arr_4d.shape}")

# Using axis parameter
sum_last_two = np.sum(arr_4d, axis=(-2, -1))
print(f"Sum over last two axes shape: {sum_last_two.shape}")

4D array shape: (2, 3, 4, 5)
Sum over last two axes shape: (2, 3)


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [25]:
D = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
S = np.array([0, 0, 1, 1, 1, 2, 2, 0, 1, 2])  # Subset labels

print(f"Data D: {D}")
print(f"Subset labels S: {S}")

#Using bincount - Count number of occurrences of each value in array of non-negative ints.
subset_sums = np.bincount(S, weights=D)
subset_counts = np.bincount(S)
subset_means = subset_sums / subset_counts
print(f"Subset means: {subset_means}")

Data D: [ 1  2  3  4  5  6  7  8  9 10]
Subset labels S: [0 0 1 1 1 2 2 0 1 2]
Subset means: [3.66666667 5.25       7.66666667]


#### 69. How to get the diagonal of a dot product? (★★★)

In [27]:
A = np.random.randint(0, 10, (4, 3))
B = np.random.randint(0, 10, (3, 4))

print(f"A shape: {A.shape}, B shape: {B.shape}")

# Compute full dot product then diagonal
diag1 = np.diag(A @ B)
print(f"Diagonal of A@B: {diag1}")

# Element-wise then sum
diag3 = np.sum(A * B.T, axis=1)
print(f"Element-wise method: {diag3}")

A shape: (4, 3), B shape: (3, 4)
Diagonal of A@B: [ 57  36  59 124]
Element-wise method: [ 57  36  59 124]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [29]:
original = np.array([1, 2, 3, 4, 5])
print(f"Original: {original}")

# Using repeat and reshape
n_zeros = 3
result_size = len(original) + (len(original) - 1) * n_zeros
result = np.zeros(result_size, dtype=original.dtype)
result[::n_zeros + 1] = original
print(f"With 3 zeros interleaved: {result}")

#2
interleaved = []
for i, val in enumerate(original):
    interleaved.append(val)
    if i < len(original) - 1:  # Don't add zeros after last element
        interleaved.extend([0] * n_zeros)
result2 = np.array(interleaved)
print(f"Alternative method: {result2}")

Original: [1 2 3 4 5]
With 3 zeros interleaved: [1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]
Alternative method: [1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [31]:
arr_3d = np.random.randint(1, 10, (5, 5, 3))
arr_2d = np.random.randint(1, 5, (5, 5))

print(f"3D array shape: {arr_3d.shape}")
print(f"2D array shape: {arr_2d.shape}")

#Using broadcasting with newaxis
result1 = arr_3d * arr_2d[:, :, np.newaxis]
print(f"Shape of result: {result1.shape}")

3D array shape: (5, 5, 3)
2D array shape: (5, 5)
Shape of result: (5, 5, 3)


#### 72. How to swap two rows of an array? (★★★)

In [35]:
matrix = np.arange(20).reshape(4, 5)
print(f"Original matrix:\n{matrix}")
print()
#Using advanced indexing
matrix_copy1 = matrix.copy()
matrix_copy1[[0, 2]] = matrix_copy1[[2, 0]]
print(f"After swapping rows 0 and 2:\n{matrix_copy1}")

# #Using temporary variable
# matrix_copy2 = matrix.copy()
# temp = matrix_copy2[1].copy()
# matrix_copy2[1] = matrix_copy2[3]
# matrix_copy2[3] = temp
# print(f"Swapped rows 1 and 3:\n{matrix_copy2}")

Original matrix:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

After swapping rows 0 and 2:
[[10 11 12 13 14]
 [ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [15 16 17 18 19]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [36]:
# 10 triangles, each defined by 3 vertex indices
triangles = np.array([
    [0, 1, 2], [1, 2, 3], [2, 3, 4], [0, 2, 4],
    [1, 3, 5], [3, 4, 5], [0, 4, 6], [4, 5, 6],
    [1, 5, 7], [5, 6, 7]
])

print(f"Triangles shape: {triangles.shape}")

# Get all edges from triangles
edges = np.array([
    [triangles[:, 0], triangles[:, 1]],  # Edge 0-1
    [triangles[:, 1], triangles[:, 2]],  # Edge 1-2  
    [triangles[:, 2], triangles[:, 0]]   # Edge 2-0
]).transpose(1, 0, 2).reshape(-1, 2)

# Sort each edge so (a,b) and (b,a) are equivalent
edges_sorted = np.sort(edges, axis=1)

# Find unique edges
unique_edges = np.unique(edges_sorted, axis=0)
print(f"Number of unique line segments: {len(unique_edges)}")
print(f"Unique line segments:\n{unique_edges}")


Triangles shape: (10, 3)
Number of unique line segments: 14
Unique line segments:
[[0 1]
 [0 2]
 [0 4]
 [1 2]
 [1 3]
 [1 5]
 [2 3]
 [3 4]
 [4 4]
 [4 5]
 [5 5]
 [5 6]
 [6 6]
 [7 7]]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [39]:
C = np.array([2, 3, 1, 4])  # Sorted bincount result
print(f" C: {C}")

# Reconstruct array A
A = np.repeat(np.arange(len(C)), C)
print()
print(f"Reconstructed A: {A}")
print(f"Verification - np.bincount(A): {np.bincount(A)}")
print(f"Matches C: {np.array_equal(np.bincount(A), C)}")

 C: [2 3 1 4]

Reconstructed A: [0 0 1 1 1 2 3 3 3 3]
Verification - np.bincount(A): [2 3 1 4]
Matches C: True


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [ ]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
window_size = 3

print(f"Data: {data}")
print(f"Window size: {window_size}")

#Using convolution
kernel = np.ones(window_size) / window_size
averages1 = np.convolve(data, kernel, mode='valid')
print(f"Sliding averages (convolution): {averages1}")

Data: [ 1  2  3  4  5  6  7  8  9 10]
Window size: 3
Sliding averages (convolution): [2. 3. 4. 5. 6. 7. 8. 9.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [43]:
Z = np.arange(10)  # [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
window_size = 3

print(f"1D array Z: {Z}")
print()
n_rows = len(Z) - window_size + 1
result = np.zeros((n_rows, window_size), dtype=Z.dtype)
for i in range(n_rows):
    result[i] = Z[i:i + window_size]
print(f"Manual construction:\n{result}")

1D array Z: [0 1 2 3 4 5 6 7 8 9]

Manual construction:
[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [47]:
bool_arr = np.array([True, False, True, False])
print(f"Original boolean: {bool_arr}")
bool_arr ^= True  # XOR with True negates
print(f"Negated boolean: {bool_arr}")

print()

float_arr = np.array([1.5, -2.3, 4.7, -8.1])
print(f"Original float: {float_arr}")
float_arr *= -1  # Multiply by -1 inplace
print(f"Sign changed: {float_arr}")

Original boolean: [ True False  True False]
Negated boolean: [False  True False  True]

Original float: [ 1.5 -2.3  4.7 -8.1]
Sign changed: [-1.5  2.3 -4.7  8.1]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [48]:
P0 = np.array([[0, 0], [1, 1], [2, 0]])  # Start points
P1 = np.array([[1, 0], [2, 3], [3, 2]])  # End points
p = np.array([1.5, 1.5])  # Point

print(f"Line start points P0:\n{P0}")
print(f"Line end points P1:\n{P1}")
print(f"Point p: {p}")

def point_to_line_distance(p, P0, P1):
    """Calculate distance from point p to lines defined by P0, P1"""
    # Vector from P0 to P1
    line_vec = P1 - P0
    # Vector from P0 to point
    point_vec = p - P0
    
    # Project point onto line
    line_len_sq = np.sum(line_vec**2, axis=1)
    # Avoid division by zero
    line_len_sq = np.where(line_len_sq == 0, 1e-10, line_len_sq)
    
    t = np.sum(point_vec * line_vec, axis=1) / line_len_sq
    t = np.clip(t, 0, 1)  # Clamp to line segment
    
    # Closest point on line segment
    closest = P0 + t[:, np.newaxis] * line_vec
    
    # Distance from point to closest point
    distances = np.linalg.norm(p - closest, axis=1)
    return distances

distances = point_to_line_distance(p, P0, P1)
print(f"Distances from point to each line: {distances}")

Line start points P0:
[[0 0]
 [1 1]
 [2 0]]
Line end points P1:
[[1 0]
 [2 3]
 [3 2]]
Point p: [1.5 1.5]
Distances from point to each line: [1.58113883 0.2236068  1.11803399]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [52]:
P = np.array([[0.5, 0.5], [1.0, 2.0], [2.5, 1.0]])  # Multiple points

print(f"Multiple points P:\n{P}")
print()
def points_to_lines_distance(P, P0, P1):
    """Calculate distance from multiple points to multiple lines"""
    n_points = len(P)
    n_lines = len(P0)
    distances = np.zeros((n_points, n_lines))
    
    for i, point in enumerate(P):
        distances[i] = point_to_line_distance(point, P0, P1)
    
    return distances

distance_matrix = points_to_lines_distance(P, P0, P1)
print(f"Distance matrix (points × lines):\n{distance_matrix}")
print()
print(f"Shape: {distance_matrix.shape}")

Multiple points P:
[[0.5 0.5]
 [1.  2. ]
 [2.5 1. ]]

Distance matrix (points × lines):
[[0.5        0.70710678 1.58113883]
 [2.         0.4472136  1.78885438]
 [1.80277564 1.34164079 0.        ]]

Shape: (3, 3)


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [53]:
def extract_centered(array, center, shape, fill=0):
    """Extract subarray centered on given element with padding if necessary"""
    array = np.asarray(array)
    center = np.asarray(center)
    shape = np.asarray(shape)
    
    # Calculate start and end indices
    start = center - shape // 2
    end = start + shape
    
    # Create output array filled with fill value
    output = np.full(shape, fill, dtype=array.dtype)
    
    # Calculate valid regions
    valid_start = np.maximum(start, 0)
    valid_end = np.minimum(end, array.shape)
    
    # Calculate indices for output array
    out_start = valid_start - start
    out_end = out_start + (valid_end - valid_start)
    
    # Copy valid region
    if array.ndim == 1:
        if valid_start[0] < valid_end[0]:
            output[out_start[0]:out_end[0]] = array[valid_start[0]:valid_end[0]]
    elif array.ndim == 2:
        if (valid_start < valid_end).all():
            output[out_start[0]:out_end[0], out_start[1]:out_end[1]] = \
                array[valid_start[0]:valid_end[0], valid_start[1]:valid_end[1]]
    
    return output

# Test with 2D array
test_array = np.arange(25).reshape(5, 5)
print(f"Original 5x5 array:\n{test_array}")

# Extract 3x3 centered at (1,1)
result = extract_centered(test_array, [1, 1], [3, 3], fill=-1)
print(f"3x3 centered at (1,1) with padding -1:\n{result}")

# Extract 3x3 centered at (0,0) - needs padding
result2 = extract_centered(test_array, [0, 0], [3, 3], fill=-1)
print(f"3x3 centered at (0,0) with padding -1:\n{result2}")

Original 5x5 array:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
3x3 centered at (1,1) with padding -1:
[[ 0  1  2]
 [ 5  6  7]
 [10 11 12]]
3x3 centered at (0,0) with padding -1:
[[-1 -1 -1]
 [-1  0  1]
 [-1  5  6]]


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [55]:
Z = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])
window_size = 4

print(f"Original Z: {Z}")
print()
#Manual construction
n_windows = len(Z) - window_size + 1
R2 = np.array([Z[i:i+window_size] for i in range(n_windows)])
print(f"Manual construction:\n{R2}")

# #Using broadcasting
# idx = np.arange(window_size)[None, :] + np.arange(n_windows)[:, None]
# R3 = Z[idx]
# print(f"Using broadcasting:\n{R3}")


Original Z: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]

Manual construction:
[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [56]:
full_rank = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 10]])  # Rank 3
rank_deficient = np.array([[1, 2, 3], [4, 5, 6], [5, 7, 9]])  # Rank 2

print(f"Full rank matrix:\n{full_rank}")
print(f"Rank: {np.linalg.matrix_rank(full_rank)}")

print(f"Rank deficient matrix:\n{rank_deficient}")
print(f"Rank: {np.linalg.matrix_rank(rank_deficient)}")


Full rank matrix:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]
Rank: 3
Rank deficient matrix:
[[1 2 3]
 [4 5 6]
 [5 7 9]]
Rank: 2


#### 83. How to find the most frequent value in an array?

In [57]:
arr = np.array([1, 2, 2, 3, 2, 4, 2, 5, 3, 3])
print(f"Array: {arr}")

# Using bincount (for positive integers)
if arr.min() >= 0:
    counts = np.bincount(arr)
    most_frequent = np.argmax(counts)
    print(f"Most frequent (bincount): {most_frequent}")

Array: [1 2 2 3 2 4 2 5 3 3]
Most frequent (bincount): 2


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [61]:
np.random.seed(42)
matrix = np.random.randint(0, 10, (10, 10))
block_size = 3

print(f"Original 10x10 matrix:\n{matrix}")
print()
#  Using stride_tricks
def extract_blocks(array, block_shape):
    """Extract all blocks of given shape from array"""
    from numpy.lib.stride_tricks import sliding_window_view
    return sliding_window_view(array, block_shape)

blocks = extract_blocks(matrix, (block_size, block_size))
print(f"Blocks shape: {blocks.shape}")  # Should be (8, 8, 3, 3)
print(f"\nFirst block (top-left):\n{blocks[0, 0]}")
print(f"\nSecond block (shifted right):\n{blocks[0, 1]}")

Original 10x10 matrix:
[[6 3 7 4 6 9 2 6 7 4]
 [3 7 7 2 5 4 1 7 5 1]
 [4 0 9 5 8 0 9 2 6 3]
 [8 2 4 2 6 4 8 6 1 3]
 [8 1 9 8 9 4 1 3 6 7]
 [2 0 3 1 7 3 1 5 5 9]
 [3 5 1 9 1 9 3 7 6 8]
 [7 4 1 4 7 9 8 8 0 8]
 [6 8 7 0 7 7 2 0 7 2]
 [2 0 4 9 6 9 8 6 8 7]]

Blocks shape: (8, 8, 3, 3)

First block (top-left):
[[6 3 7]
 [3 7 7]
 [4 0 9]]

Second block (shifted right):
[[3 7 4]
 [7 7 2]
 [0 9 5]]


#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [62]:
class SymmetricArray(np.ndarray):
    """2D array where Z[i,j] == Z[j,i]"""
    
    def __new__(cls, input_array):
        obj = np.asarray(input_array).view(cls)
        if obj.ndim != 2 or obj.shape[0] != obj.shape[1]:
            raise ValueError("Array must be 2D and square")
        return obj
    
    def __setitem__(self, key, value):
        super().__setitem__(key, value)
        # If setting single element, also set symmetric element
        if isinstance(key, tuple) and len(key) == 2:
            i, j = key
            if isinstance(i, int) and isinstance(j, int) and i != j:
                super().__setitem__((j, i), value)

# Test symmetric array
sym_arr = SymmetricArray(np.eye(4))
print(f"Original symmetric array:\n{sym_arr}")

sym_arr[1, 3] = 5  # This should also set [3, 1] = 5
print(f"After setting [1,3] = 5:\n{sym_arr}")
print(f"Verification: [1,3] = {sym_arr[1,3]}, [3,1] = {sym_arr[3,1]}")


Original symmetric array:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
After setting [1,3] = 5:
[[1. 0. 0. 0.]
 [0. 1. 0. 5.]
 [0. 0. 1. 0.]
 [0. 5. 0. 1.]]
Verification: [1,3] = 5.0, [3,1] = 5.0


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [65]:
p, n = 3, 4
np.random.seed(42)
matrices = np.random.randint(1, 5, (p, n, n))  # p matrices of shape (n,n)
vectors = np.random.randint(1, 5, (p, n, 1))   # p vectors of shape (n,1)

print(f"Shapes: {p} matrices {matrices.shape}, {p} vectors {vectors.shape}")

#Using einsum
result1 = np.einsum('pij,pjk->ik', matrices, vectors).sum(axis=0, keepdims=True)
print(f"Result shape using einsum: {result1.shape}")

#Loop and sum
result2 = np.zeros((n, 1))
for i in range(p):
    result2 += matrices[i] @ vectors[i]
print(f"Result shape using loop: {result2.shape}")

Shapes: 3 matrices (3, 4, 4), 3 vectors (3, 4, 1)
Result shape using einsum: (1, 1)
Result shape using loop: (4, 1)


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [68]:
np.random.seed(42)
large_array = np.random.randint(0, 10, (16, 16))
block_size = 4

print(f"Original array shape: {large_array.shape}")

#Using reshape and sum
def block_sum_reshape(array, block_size):
    """Sum blocks using reshape"""
    h, w = array.shape
    return array.reshape(h//block_size, block_size, w//block_size, block_size).sum(axis=(1, 3))

block_sums1 = block_sum_reshape(large_array, block_size)
print(f"\nBlock sums shape: {block_sums1.shape}")
print(f"\nBlock sums:\n{block_sums1}")


Original array shape: (16, 16)

Block sums shape: (4, 4)

Block sums:
[[65 73 86 72]
 [80 83 78 71]
 [67 58 69 78]
 [72 69 61 68]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [69]:
def game_of_life_step(grid):
    """Single step of Conway's Game of Life"""
    # Count neighbors using convolution
    kernel = np.array([[1, 1, 1],
                       [1, 0, 1],
                       [1, 1, 1]])
    
    # Pad grid to handle boundaries
    padded = np.pad(grid, 1, mode='constant', constant_values=0)
    neighbor_count = np.zeros_like(grid)
    
    # Count neighbors manually (alternative to scipy.ndimage.convolve)
    for i in range(3):
        for j in range(3):
            if i == 1 and j == 1:
                continue
            neighbor_count += padded[i:i+grid.shape[0], j:j+grid.shape[1]]
    
    # Apply Game of Life rules
    # Live cell with 2-3 neighbors survives
    # Dead cell with exactly 3 neighbors becomes alive
    new_grid = np.zeros_like(grid)
    new_grid[(grid == 1) & ((neighbor_count == 2) | (neighbor_count == 3))] = 1
    new_grid[(grid == 0) & (neighbor_count == 3)] = 1
    
    return new_grid

# Test with a glider pattern
glider = np.array([[0, 1, 0, 0, 0],
                   [0, 0, 1, 0, 0],
                   [1, 1, 1, 0, 0],
                   [0, 0, 0, 0, 0],
                   [0, 0, 0, 0, 0]])

print("Initial glider pattern:")
print(glider)

# Run a few steps
current = glider.copy()
for step in range(3):
    current = game_of_life_step(current)
    print(f"\nStep {step + 1}:")
    print(current)

Initial glider pattern:
[[0 1 0 0 0]
 [0 0 1 0 0]
 [1 1 1 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]

Step 1:
[[0 0 0 0 0]
 [1 0 1 0 0]
 [0 1 1 0 0]
 [0 1 0 0 0]
 [0 0 0 0 0]]

Step 2:
[[0 0 0 0 0]
 [0 0 1 0 0]
 [1 0 1 0 0]
 [0 1 1 0 0]
 [0 0 0 0 0]]

Step 3:
[[0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 1 0]
 [0 1 1 0 0]
 [0 0 0 0 0]]


#### 89. How to get the n largest values of an array (★★★)

In [70]:
arr = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3])
n = 4

print(f"Array: {arr}")

# Method 1: Using argpartition (most efficient)
indices = np.argpartition(arr, -n)[-n:]
largest_values = arr[indices[np.argsort(arr[indices])[::-1]]]
print(f"{n} largest values (argpartition): {largest_values}")

Array: [3 1 4 1 5 9 2 6 5 3]
4 largest values (argpartition): [9 6 5 5]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [ ]:
def cartesian_product(*arrays):
    """Compute cartesian product of input arrays"""
    arrays = [np.asarray(x) for x in arrays]
    dtype = np.find_common_type([x.dtype for x in arrays], [])
    
    n = len(arrays)
    if n == 0:
        return np.array([])
    
    # Calculate total size
    size = 1
    for x in arrays:
        size *= len(x)
    
    # Create output array
    result = np.zeros((size, n), dtype=dtype)
    
    # Fill result using meshgrid
    grids = np.meshgrid(*arrays, indexing='ij')
    for i, grid in enumerate(grids):
        result[:, i] = grid.flatten()
    
    return result

# Test with multiple vectors
a = np.array([1, 2])
b = np.array([10, 20, 30])
c = np.array([100, 200])

print(f"Vector a: {a}")
print(f"Vector b: {b}")
print(f"Vector c: {c}")

cart_prod = cartesian_product(a, b, c)
print(f"Cartesian product shape: {cart_prod.shape}")
print(f"Cartesian product:\n{cart_prod}")

#### 91. How to create a record array from a regular array? (★★★)

In [73]:
# Regular 2D array
regular_array = np.array([[1, 2.5, 'Alice'],
                         [2, 3.7, 'Bob'],
                         [3, 1.2, 'Charlie']], dtype=object)

print(f"Regular array:\n{regular_array}")

# structured array with explicit dtype
dt = np.dtype([('id', 'i4'), ('score', 'f4'), ('name', 'U10')])
record_array = np.zeros(3, dtype=dt)
record_array['id'] = [1, 2, 3]
record_array['score'] = [2.5, 3.7, 1.2]
record_array['name'] = ['Alice', 'Bob', 'Charlie']

print(f"\nRecord array:\n{record_array}")
print(f"\nAccess by field - names: {record_array['name']}")
print(f"\nAccess by field - scores: {record_array['score']}")


Regular array:
[[1 2.5 'Alice']
 [2 3.7 'Bob']
 [3 1.2 'Charlie']]

Record array:
[(1, 2.5, 'Alice') (2, 3.7, 'Bob') (3, 1.2, 'Charlie')]

Access by field - names: ['Alice' 'Bob' 'Charlie']

Access by field - scores: [2.5 3.7 1.2]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [76]:
np.random.seed(42)
Z = np.random.random(1000000)  # Large vector for timing comparison

print(f"Vector size: {len(Z)}")

# Using ** operator
Z_cubed1 = Z ** 3

#Using np.power
Z_cubed2 = np.power(Z, 3)

#Using repeated multiplication
Z_cubed3 = Z * Z * Z

print(Z_cubed1)
print(Z_cubed2)

Vector size: 1000000
[0.0525406  0.85931044 0.39221343 ... 0.07307237 0.07877222 0.802927  ]
[0.0525406  0.85931044 0.39221343 ... 0.07307237 0.07877222 0.802927  ]


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [80]:
np.random.seed(42)
A = np.random.randint(1, 6, (8, 3))
B = np.array([[2, 3], [1, 4]])

print(f"Array A (8x3):\n{A}")
print(f"\nArray B (2x2):\n{B}")

def find_rows_containing_elements(A, B):
    """Find rows of A that contain all elements of each row of B"""
    result = []
    for b_row in B:
        # For each row in B, find rows in A that contain all elements
        contains_all = np.array([np.isin(b_row, a_row).all() for a_row in A])
        result.append(np.where(contains_all)[0])
    return result

matching_rows = find_rows_containing_elements(A, B)
print(f"\nRows of A containing all elements of B[0] {B[0]}: {matching_rows[0]}")
print(f"\nRows of A containing all elements of B[1] {B[1]}: {matching_rows[1]}")

# Show the actual matching rows
for i, row_indices in enumerate(matching_rows):
    print(f"For B[{i}] = {B[i]}:")
    for idx in row_indices:
        print(f"  A[{idx}] = {A[idx]}")

Array A (8x3):
[[4 5 3]
 [5 5 2]
 [3 3 3]
 [5 4 3]
 [5 2 4]
 [2 4 5]
 [1 4 2]
 [5 4 1]]

Array B (2x2):
[[2 3]
 [1 4]]

Rows of A containing all elements of B[0] [2 3]: []

Rows of A containing all elements of B[1] [1 4]: [6 7]
For B[0] = [2 3]:
For B[1] = [1 4]:
  A[6] = [1 4 2]
  A[7] = [5 4 1]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [83]:
np.random.seed(42)
matrix = np.random.randint(1, 4, (10, 3))
# Ensure some rows have equal values
matrix[2] = [2, 2, 2]
matrix[5] = [3, 3, 3]

print(f"10x3 matrix:\n{matrix}")

# Check if all elements in row are equal
unequal_mask = ~np.all(matrix == matrix[:, [0]], axis=1)
unequal_rows = matrix[unequal_mask]

print(f"\nRows with unequal values:\n{unequal_rows}")

# # Using std (standard deviation > 0 means unequal)
# unequal_mask2 = np.std(matrix, axis=1) > 0
# unequal_rows2 = matrix[unequal_mask2]

# print(f"Using std method - same result: {np.array_equal(unequal_rows, unequal_rows2)}")

# #Check uniqueness
# unequal_mask3 = np.array([len(np.unique(row)) > 1 for row in matrix])
# unequal_rows3 = matrix[unequal_mask3]

# print(f"Using unique method - same result: {np.array_equal(unequal_rows, unequal_rows3)}")

10x3 matrix:
[[3 1 3]
 [3 1 1]
 [2 2 2]
 [3 3 3]
 [1 3 2]
 [3 3 3]
 [2 2 1]
 [1 2 2]
 [1 1 1]
 [3 3 3]]

Rows with unequal values:
[[3 1 3]
 [3 1 1]
 [1 3 2]
 [2 2 1]
 [1 2 2]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [ ]:
vector = np.array([5, 10, 15, 20])
print(f"Integer vector: {vector}")

# Using np.unpackbits
def int_to_binary_matrix(arr, bits=8):
    """Convert integers to binary matrix representation"""
    # Ensure we can represent the numbers
    max_bits = int(np.ceil(np.log2(np.max(arr) + 1))) if np.max(arr) > 0 else 1
    bits = max(bits, max_bits)
    
    # Convert to bytes then unpack bits
    # For simplicity, manual bit extraction
    binary_matrix = np.zeros((len(arr), bits), dtype=int)
    
    for i, num in enumerate(arr):
        binary_str = format(num, f'0{bits}b')
        binary_matrix[i] = [int(b) for b in binary_str]
    
    return binary_matrix

binary_repr = int_to_binary_matrix(vector, bits=8)
print(f"Binary representation (8 bits):\n{binary_repr}")

# Verify by converting back
decimal_check = np.sum(binary_repr * (2 ** np.arange(7, -1, -1)), axis=1)
print(f"Converted back to decimal: {decimal_check}")
print(f"Matches original: {np.array_equal(vector, decimal_check)}")


Integer vector: [ 5 10 15 20]
Binary representation (8 bits):
[[0 0 0 0 0 1 0 1]
 [0 0 0 0 1 0 1 0]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 1 0 0]]
Converted back to decimal: [ 5 10 15 20]
Matches original: True


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [85]:
# Create array with some duplicate rows
arr_with_dups = np.array([[1, 2, 3],
                         [4, 5, 6],
                         [1, 2, 3],  # Duplicate
                         [7, 8, 9],
                         [4, 5, 6],  # Duplicate
                         [10, 11, 12]])

print(f"Array with duplicates:\n{arr_with_dups}")

# Method 1: Using np.unique
unique_rows1 = np.unique(arr_with_dups, axis=0)
print(f"Unique rows (np.unique):\n{unique_rows1}")

Array with duplicates:
[[ 1  2  3]
 [ 4  5  6]
 [ 1  2  3]
 [ 7  8  9]
 [ 4  5  6]
 [10 11 12]]
Unique rows (np.unique):
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [86]:
A = np.random.randint(1, 5, (3, 4))
B = np.random.randint(1, 5, (4, 3))

print(f"A shape: {A.shape}")
print(f"B shape: {B.shape}")

# Inner product (when shapes match)
A_vec = np.array([1, 2, 3, 4])
B_vec = np.array([2, 3, 4, 5])

inner_standard = np.inner(A_vec, B_vec)
inner_einsum = np.einsum('i,i->', A_vec, B_vec)
print(f"Inner product - standard: {inner_standard}, einsum: {inner_einsum}")

# Outer product
outer_standard = np.outer(A_vec, B_vec)
outer_einsum = np.einsum('i,j->ij', A_vec, B_vec)
print(f"Outer product shapes - standard: {outer_standard.shape}, einsum: {outer_einsum.shape}")
print(f"Outer products equal: {np.array_equal(outer_standard, outer_einsum)}")

# Sum
sum_standard = np.sum(A)
sum_einsum = np.einsum('ij->', A)
print(f"Sum - standard: {sum_standard}, einsum: {sum_einsum}")

# Element-wise multiplication
mul_standard = A[:3, :3] * B[:3, :3]  # Make shapes compatible
mul_einsum = np.einsum('ij,ij->ij', A[:3, :3], B[:3, :3])
print(f"Element-wise multiplication equal: {np.array_equal(mul_standard, mul_einsum)}")

# Matrix multiplication
matmul_standard = A @ B
matmul_einsum = np.einsum('ij,jk->ik', A, B)
print(f"Matrix multiplication equal: {np.array_equal(matmul_standard, matmul_einsum)}")

A shape: (3, 4)
B shape: (4, 3)
Inner product - standard: 40, einsum: 40
Outer product shapes - standard: (4, 4), einsum: (4, 4)
Outer products equal: True
Sum - standard: 37, einsum: 37
Element-wise multiplication equal: True
Matrix multiplication equal: True


#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [87]:
# Create a curved path
t = np.linspace(0, 4*np.pi, 100)
X = np.sin(t) * t / 4
Y = np.cos(t) * t / 4

print(f"Original path has {len(X)} points")

def sample_path_equidistant(X, Y, n_samples):
    """Sample path with equidistant samples"""
    # Calculate cumulative distance along path
    diffs = np.diff(np.column_stack([X, Y]), axis=0)
    distances = np.sqrt(np.sum(diffs**2, axis=1))
    cumulative_distance = np.concatenate([[0], np.cumsum(distances)])
    
    # Create equidistant sample points
    total_distance = cumulative_distance[-1]
    sample_distances = np.linspace(0, total_distance, n_samples)
    
    # Interpolate X and Y at sample distances
    X_sampled = np.interp(sample_distances, cumulative_distance, X)
    Y_sampled = np.interp(sample_distances, cumulative_distance, Y)
    
    return X_sampled, Y_sampled

# Sample with 20 equidistant points
X_sampled, Y_sampled = sample_path_equidistant(X, Y, 20)
print(f"Sampled to {len(X_sampled)} equidistant points")

# Verify distances are approximately equal
diffs_sampled = np.diff(np.column_stack([X_sampled, Y_sampled]), axis=0)
distances_sampled = np.sqrt(np.sum(diffs_sampled**2, axis=1))
print(f"Sample distances - mean: {np.mean(distances_sampled):.4f}, std: {np.std(distances_sampled):.4f}")

Original path has 100 points
Sampled to 20 equidistant points
Sample distances - mean: 1.0225, std: 0.0941


#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [90]:
# Create test array
test_array = np.array([[1, 2, 2],      # Sum = 5
                      [3, 1, 1],       # Sum = 5  
                      [2, 1, 2, 0],    # Sum = 5
                      [1.5, 2, 1.5],   # Sum = 5 but not integers
                      [2, 2, 2],       # Sum = 6
                      [1, 1, 1, 1, 1], # Sum = 5
                      [0, 0, 5]])      # Sum = 5

n = 5
print(f"Test array with target sum n={n}:")
for i, row in enumerate(test_array):
    print(f"Row {i}: {row} (sum={np.sum(row)})")

def select_multinomial_rows(X, n):
    """Select rows that could be multinomial draws with n degrees"""
    valid_rows = []
    
    for i, row in enumerate(X):
        # Check if all elements are non-negative integers
        if np.all(row >= 0) and np.all(row == np.asarray(row, dtype=int)):
            # Check if sum equals n
            if np.sum(row) == n:
                valid_rows.append(i)
    
    return np.array(valid_rows)

valid_indices = select_multinomial_rows(test_array, n)
print(f"Valid multinomial rows (indices): {valid_indices}")

print("Valid rows:")
for idx in valid_indices:
    print(f"Row {idx}: {test_array[idx]}")

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (7,) + inhomogeneous part.

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [89]:
np.random.seed(42)
X = np.random.normal(10, 2, 1000)  # Sample data
N = 10000  # Number of bootstrap samples

print(f"Original data: mean={np.mean(X):.3f}, std={np.std(X):.3f}, n={len(X)}")

def bootstrap_confidence_interval(data, n_bootstrap=10000, confidence=0.95):
    """Compute bootstrap confidence interval for the mean"""
    n = len(data)
    bootstrap_means = []
    
    for _ in range(n_bootstrap):
        # Resample with replacement
        bootstrap_sample = np.random.choice(data, size=n, replace=True)
        bootstrap_means.append()

Original data: mean=10.039, std=1.957, n=1000
