# Numpy Exercise 3

### All of the questions in this exercise are attributed to rougier/numpy-100

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

Why it's not recommended:

- Hidden bugs: Warnings often indicate real problems in your code
- Debugging difficulty: You lose valuable diagnostic information
- Silent failures: Operations may produce unexpected results without notice
- Maintenance issues: Future developers won't see important warnings

In [2]:
import numpy as np
import warnings

# Ignore all numpy warnings
warnings.filterwarnings('ignore', category=np.VisibleDeprecationWarning)
warnings.filterwarnings('ignore', category=np.ComplexWarning)
warnings.filterwarnings('ignore', category=np.RankWarning)

# Or more broadly, ignore all warnings from numpy
warnings.filterwarnings('ignore', module='numpy')

AttributeError: module 'numpy' has no attribute 'VisibleDeprecationWarning'

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [4]:
import numpy as np

# Regular sqrt returns nan (with a warning)
result1 = np.sqrt(-1)  

# emath.sqrt returns complex number
result2 = np.emath.sqrt(-1)  

print(f"np.sqrt(-1) = {result1}")     
print()      
print(f"np.emath.sqrt(-1) = {result2}")    
print()
print(f"Are they equal? {result1 == result2}")  # False

# nan is never equal to anything, including itself
# print(f"nan == nan: {np.nan == np.nan}")   

np.sqrt(-1) = nan

np.emath.sqrt(-1) = 1j

Are they equal? False


C:\Users\Administrator\AppData\Local\Temp\ipykernel_3972\141681881.py:4: RuntimeWarning: invalid value encountered in sqrt
  result1 = np.sqrt(-1)


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [8]:
import numpy as np

# Method 1: Using numpy datetime
today = np.datetime64('today')
yesterday = today - np.timedelta64(1, 'D')
tomorrow = today + np.timedelta64(1, 'D')

print(f"Yesterday: {yesterday}")
print(f"Today: {today}")
print(f"Tomorrow: {tomorrow}")
print()
# Method 2: More explicit
today = np.datetime64('today', 'D')
yesterday = today - 1
tomorrow = today + 1
print(f"Yesterday: {yesterday}")
print(f"Today: {today}")
print(f"Tomorrow: {tomorrow}")

Yesterday: 2025-07-27
Today: 2025-07-28
Tomorrow: 2025-07-29

Yesterday: 2025-07-27
Today: 2025-07-28
Tomorrow: 2025-07-29


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [ ]:
import numpy as np

# Method 1: Using arange
july_2016 = np.arange('2016-07-01', '2016-08-01', dtype='datetime64[D]')
print(f"July 2016 dates: {july_2016}")

# # Method 2: More explicit range
# start = np.datetime64('2016-07-01')
# end = np.datetime64('2016-08-01') #excusive end
# july_2016 = np.arange(start, end, dtype='datetime64[D]')

# # Method 3: Using timedelta
# start = np.datetime64('2016-07-01')
# july_2016 = start + np.arange(31)  # July has 31 days
print()
print(f"Number of days: {len(july_2016)}")
print(f"First day: {july_2016[0]}")
print(f"Last day: {july_2016[-1]}")

July 2016 dates: ['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']

Number of days: 31
First day: 2016-07-01
Last day: 2016-07-31


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

The "in-place" constraint means we can't create large temporary arrays, but we still need to preserve the original A values somehow - either in a small temp variable or by reusing existing memory (like array B).


In [ ]:
import numpy as np

A = np.array([2., 4., 6.])
B = np.array([1., 2., 3.])
original_A = A.copy()  #as control
# Expected result: ([3, 6, 9] * [-1, -2, -3]) = [-3, -12, -27]

# Method 1: Using a temporary variable
def compute_inplace_v1(A, B):
    temp = A.copy()  # Small temporary copy
    A += B           # A = A + B (in-place)
    temp /= -2       # temp = -A/2
    A *= temp        # A = (A+B) * (-A/2) (in-place)
    return A
result = compute_inplace_v1(A, B)
print(result)  


# # Method 2: Carefully ordered operations
# def compute_inplace_v2(A, B):
#     # We need to be very careful about order
#     A /= -2          # A = -A/2 (in-place)
#     A *= (original_A + B)  # This requires original A values
#     return A
# result = compute_inplace_v2(A, B)
# print(result)

# # Method 3: Most memory-efficient (reusing B if allowed)
# def compute_inplace_v3(A, B):
#     B += A           # B = A + B (reuse B as temp)
#     A /= -2          # A = -A/2
#     A *= B           # A = (A+B) * (-A/2)
#     return A
# result = compute_inplace_v3(A, B)
# print(result) 


[ -3. -12. -27.]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [ ]:
import numpy as np

# Create random array of positive numbers
arr = np.random.uniform(1, 100, 10)
print(f"Original array: {arr}")

# Method 1: Using astype
method1 = arr.astype(int)

# Method 2: Using np.floor
method2 = np.floor(arr).astype(int)

# Method 3: Using np.trunc
method3 = np.trunc(arr).astype(int)

# Method 4: Using modulo arithmetic
method4 = arr - arr % 1

print(f"Method 1 (astype): {method1}")
print(f"Method 2 (floor): {method2}")
print(f"Method 3 (trunc): {method3}")
print(f"Method 4 (modulo): {method4}")

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [36]:
import numpy as np

# Method 1: Using broadcasting
matrix1 = np.zeros((5, 5)) + np.arange(5)
print(np.zeros((5, 5)))
print(np.arange(5))
print((np.arange(5), 5))
print()

# Method 2: Using tile
matrix2 = np.tile(np.arange(5), (5, 1))

# Method 3: Using repeat and reshape
matrix3 = np.repeat(np.arange(5), 5).reshape(5, 5)

# Method 4: Using broadcasting with newaxis
matrix4 = np.arange(5)[np.newaxis, :] + np.zeros((5, 1))

print("Method 1 (broadcasting):")
print(matrix1)
print("\nMethod 2 (tile):")
print(matrix2)
print("\nMethod 3")
print(matrix3)
print("\nMethod 4")
print(matrix4)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[0 1 2 3 4]
(array([0, 1, 2, 3, 4]), 5)

Method 1 (broadcasting):
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]

Method 2 (tile):
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]

Method 3
[[0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]]

Method 4
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

Generator is a Python function that yields values one at a time, rather than computing and storing all values at once.


In [40]:
import numpy as np

# Define generator function
def generate_integers():
    for i in range(10):
        yield i ** 2  # Generate squares of 0-9

#  Using np.fromiter
# fromiter() is designed specifically for iterators/generators
arr = np.fromiter(generate_integers(), dtype=int)

# # Using list comprehension
# arr = np.array(list(generate_integers()))

# # Using np.array directly on generator
# arr = np.array([x for x in generate_integers()])

print(f"Array from generator: {arr}")


Array from generator: [ 0  1  4  9 16 25 36 49 64 81]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [ ]:
import numpy as np

# Method 1: Using linspace
vector1 = np.linspace( 0, 1, 12)[1:-1]  # Exclude first and last

# Method 2: Using arange
vector2 = np.arange(1, 10) / 11 #10/11 avoids 0 and 1

# Method 4: More precise with linspace
vector4 = np.linspace(0.1, 0.9, 10)

print(f"Method 1: {vector1}")
print(f"\nMethod 2: {vector2}")
print(f"\nMethod 4: {vector4}")

Method 1: [0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]

Method 2: [0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182]

Method 4: [0.1        0.18888889 0.27777778 0.36666667 0.45555556 0.54444444
 0.63333333 0.72222222 0.81111111 0.9       ]


#### 40. Create a random vector of size 10 and sort it (★★☆)

- np.sort(): Creates new array
- .sort(): Modifies original
- argsort(): Returns indices, useful for sorting multiple arrays consistently

In [ ]:
import numpy as np

# Create random vector
np.random.seed(42)
vector = np.random.random(10)
print(f"Original:\n {vector}")

# Method 1: Using np.sort (returns sorted copy)
sorted1 = np.sort(vector)

# Method 2: Using .sort() method (in-place)
vector_copy = vector.copy()
vector_copy.sort()

# Method 3: Using argsort for indices 
#argsort() - returns indices that would sort the array
indices = np.argsort(vector)
sorted3 = vector[indices]

print(f"Sorted:\n {sorted1}")
print(f"In-place sorted:\n {vector_copy}")
print(f"Sorted via indices:\n {sorted3}")

Original:
 [0.37454012 0.95071431 0.73199394 0.59865848 0.15601864 0.15599452
 0.05808361 0.86617615 0.60111501 0.70807258]
Sorted:
 [0.05808361 0.15599452 0.15601864 0.37454012 0.59865848 0.60111501
 0.70807258 0.73199394 0.86617615 0.95071431]
In-place sorted:
 [0.05808361 0.15599452 0.15601864 0.37454012 0.59865848 0.60111501
 0.70807258 0.73199394 0.86617615 0.95071431]
Sorted via indices:
 [0.05808361 0.15599452 0.15601864 0.37454012 0.59865848 0.60111501
 0.70807258 0.73199394 0.86617615 0.95071431]


#### 41. How to sum a small array faster than np.sum? (★★☆)
- Rough guideline:
- Arrays < 50 elements: Python sum() often faster
- Arrays > 50 elements: np.sum() becomes faster
- Arrays > 1000 elements: np.sum() much faster

In [60]:
import numpy as np

# Create small array
np.random.seed(42)
arr = np.random.random(10)
print(arr)

# Method 1: Python built-in sum (can be faster for very small arrays)
result1 = sum(arr) # Converts to Python floats and sums

# Method 2: Using np.add.reduce
result2 = np.add.reduce(arr)

# Method 4: Manual loop (for very small arrays)
result4 = 0
for x in arr:
    result4 += x

print(f"Built-in sum\n: {result1}")
print(f"np.sum\n: {np.sum(arr)}")
print(f"Manual loop\n{result4}")

# For very small arrays (< 50 elements), Python's sum() can be faster due to lower function call overhead

[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864 0.15599452
 0.05808361 0.86617615 0.60111501 0.70807258]
Built-in sum
: 5.201367359526748
np.sum
: 5.201367359526748
Manual loop
5.201367359526748


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [63]:
import numpy as np

# Create two arrays
np.random.seed(42)
A = np.random.random(5)
B = np.random.random(5)
C = A.copy()  # Make C equal to A
print(f"A: {A}")
print(f"B: {B}")
print()

# Method 1: Using np.array_equal (exact equality)
equal1 = np.array_equal(A, B)
equal2 = np.array_equal(A, C)
print(f"A == B: {equal1}")

# Method 2: Using np.allclose (approximate equality)
equal3 = np.allclose(A, B)
equal4 = np.allclose(A, C)
print(f"A == C: {equal2}")

A: [0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
B: [0.15599452 0.05808361 0.86617615 0.60111501 0.70807258]

A == B: False
A == C: True


#### 43. Make an array immutable (read-only) (★★☆)

In [68]:
import numpy as np

# Create array
arr = np.array([1, 2, 3, 4, 5])
print(f"Original: {arr}")
print(f"Writable: {arr.flags.writeable}")

# Method 1: Set writeable flag to False
arr.flags.writeable = False
print(f"Writable:{arr.flags.writeable}")

# Try to modify (this will raise an error)
try:
    arr[0] = 10
except ValueError as e:
    print(f"Error: {e}")

# Method 2: Using np.asarray with readonly
arr2 = np.array([1, 2, 3, 4, 5])
readonly_view = arr2.view()
readonly_view.flags.writeable = False

print(f"Original array can still be modified:\n {arr2}")
arr2[0] = 100
print(f"Modified original:\n {arr2}")
print(f"View reflects changes:\n {readonly_view}")

try:
    readonly_view[1] = 88
except ValueError as e:
    print(f"View modification error: {e}")

Original: [1 2 3 4 5]
Writable: True
Writable:False
Error: assignment destination is read-only
Original array can still be modified:
 [1 2 3 4 5]
Modified original:
 [100   2   3   4   5]
View reflects changes:
 [100   2   3   4   5]
View modification error: assignment destination is read-only


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

- Cartesian coordinates can be used in three dimensions (x, y, and z), polar coordinates only specify two dimensions (r and θ).

In [ ]:
import numpy as np

# Create random 10x2 matrix (x, y coordinates)
np.random.seed(42)
cartesian = np.random.uniform(-10, 10, (10, 2))
print("Cartesian coordinates (x, y)")
print(cartesian)

# Extract x and y
x, y = cartesian[:, 0], cartesian[:, 1]
# x = cartesian[:, 0]  # Extract x coordinates
# y = cartesian[:, 1]  # Extract y coordinates

# Convert to polar coordinates
# r = sqrt(x² + y²)
# θ = arctan2(y, x)
r = np.sqrt(x**2 + y**2) # Distance from origin
theta = np.arctan2(y, x)  # Angle from positive x-axis

# Combine into polar coordinate matrix
polar = np.column_stack((r, theta))

print("\nPolar coordinates (r, θ):")
print(polar)

# Convert theta to degrees if desired
theta_degrees = np.degrees(theta)
polar_degrees = np.column_stack((r, theta_degrees))
print("\nPolar coordinates (r, θ in degrees):")
print(polar_degrees)

Cartesian coordinates (x, y)
[[-2.50919762  9.01428613]
 [ 4.63987884  1.97316968]
 [-6.87962719 -6.88010959]
 [-8.83832776  7.32352292]
 [ 2.02230023  4.16145156]
 [-9.58831011  9.39819704]
 [ 6.64885282 -5.75321779]
 [-6.36350066 -6.3319098 ]
 [-3.91515514  0.49512863]
 [-1.36109963 -4.1754172 ]]

Polar coordinates (r, θ):
[[ 9.35699883  1.84228165]
 [ 5.04201093  0.40209355]
 [ 9.72960319 -2.35615943]
 [11.47824139  2.44964866]
 [ 4.6268107   1.11844343]
 [13.42616097  2.36620722]
 [ 8.79242621 -0.71330674]
 [ 8.97703862 -2.35868285]
 [ 3.94633908  3.01579583]
 [ 4.39166266 -1.88591373]]

Polar coordinates (r, θ in degrees):
[[   9.35699883  105.55496316]
 [   5.04201093   23.03826351]
 [   9.72960319 -134.99799127]
 [  11.47824139  140.35452948]
 [   4.6268107    64.08208829]
 [  13.42616097  135.57368701]
 [   8.79242621  -40.8694658 ]
 [   8.97703862 -135.14257269]
 [   3.94633908  172.79237271]
 [   4.39166266 -108.05489699]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [75]:
import numpy as np

# Create random vector
np.random.seed(42)
vector = np.random.randint(10, size=10)
print(f"Original vector: {vector}")

# Using argmax (replaces first occurrence only)
vector_copy1 = vector.copy()
vector_copy1[np.argmax(vector_copy1)] = 0

#Using boolean indexing (replaces ALL max values)
vector_copy2 = vector.copy()
vector_copy2[vector_copy2 == vector_copy2.max()] = 0

# Using np.where
vector_copy3 = np.where(vector == vector.max(), 0, vector)


print(f"Max replaced (argmax): {vector_copy1}")
print(f"Max replaced (boolean indexing): {vector_copy2}")
print(f"Max replaced (np.where): {vector_copy3}")


Original vector: [6 3 7 4 6 9 2 6 7 4]
Max replaced (argmax): [6 3 7 4 6 0 2 6 7 4]
Max replaced (boolean indexing): [6 3 7 4 6 0 2 6 7 4]
Max replaced (np.where): [6 3 7 4 6 0 2 6 7 4]
